from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinkedinScraper(object):
    def setupUi(self, LinkedinScraper):
        LinkedinScraper.setObjectName("LinkedinScraper")
        LinkedinScraper.resize(507, 692)
        self.centralwidget = QtWidgets.QWidget(parent=LinkedinScraper)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Body = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bodyTop = QtWidgets.QWidget(parent=self.Body)
        self.bodyTop.setObjectName("bodyTop")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bodyTop)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleBodyLbl = QtWidgets.QLabel(parent=self.bodyTop)
        self.titleBodyLbl.setObjectName("titleBodyLbl")
        self.verticalLayout_2.addWidget(self.titleBodyLbl, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout.addWidget(self.bodyTop, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.bodyBottom = QtWidgets.QWidget(parent=self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyBottom.sizePolicy().hasHeightForWidth())
        self.bodyBottom.setSizePolicy(sizePolicy)
        self.bodyBottom.setObjectName("bodyBottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bodyBottom)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.bodyBottom)
        self.stackedWidget.setObjectName("stackedWidget")
        self.formPage = QtWidgets.QWidget()
        self.formPage.setObjectName("formPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.formPage)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formPageWidget = QtWidgets.QWidget(parent=self.formPage)
        self.formPageWidget.setObjectName("formPageWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formPageWidget)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formPageWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.jobTitleLineEdit = QtWidgets.QLineEdit(parent=self.formPageWidget)
        self.jobTitleLineEdit.setObjectName("jobTitleLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.jobTitleLineEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.formPageWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.CountryComboBox = QtWidgets.QComboBox(parent=self.formPageWidget)
        self.CountryComboBox.setObjectName("CountryComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.CountryComboBox)
        self.label_3 = QtWidgets.QLabel(parent=self.formPageWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_3)
        self.cityLineEdit = QtWidgets.QLineEdit(parent=self.formPageWidget)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.cityLineEdit)
        self.label_6 = QtWidgets.QLabel(parent=self.formPageWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.includeKeyLineEdit = QtWidgets.QLineEdit(parent=self.formPageWidget)
        self.includeKeyLineEdit.setObjectName("includeKeyLineEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.includeKeyLineEdit)
        self.label_7 = QtWidgets.QLabel(parent=self.formPageWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.excludeKeyLineEdit = QtWidgets.QLineEdit(parent=self.formPageWidget)
        self.excludeKeyLineEdit.setObjectName("excludeKeyLineEdit")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.excludeKeyLineEdit)
        self.startScraperBtn = QtWidgets.QPushButton(parent=self.formPageWidget)
        self.startScraperBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.startScraperBtn.setObjectName("startScraperBtn")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.ItemRole.FieldRole, self.startScraperBtn)
        self.verticalLayout_4.addWidget(self.formPageWidget)
        self.stackedWidget.addWidget(self.formPage)
        self.resultPage = QtWidgets.QWidget()
        self.resultPage.setObjectName("resultPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.resultPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resultPageWidget = QtWidgets.QWidget(parent=self.resultPage)
        self.resultPageWidget.setObjectName("resultPageWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.resultPageWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.emailsListWidget = QtWidgets.QListWidget(parent=self.resultPageWidget)
        self.emailsListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.emailsListWidget.setIconSize(QtCore.QSize(64, 64))
        self.emailsListWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.emailsListWidget.setMovement(QtWidgets.QListView.Movement.Static)
        self.emailsListWidget.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.emailsListWidget.setProperty("isWrapping", False)
        self.emailsListWidget.setResizeMode(QtWidgets.QListView.ResizeMode.Fixed)
        self.emailsListWidget.setLayoutMode(QtWidgets.QListView.LayoutMode.Batched)
        self.emailsListWidget.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.emailsListWidget.setSelectionRectVisible(False)
        self.emailsListWidget.setObjectName("emailsListWidget")
        self.verticalLayout_6.addWidget(self.emailsListWidget)
        self.widget_2 = QtWidgets.QWidget(parent=self.resultPageWidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.stopBtn = QtWidgets.QPushButton(parent=self.widget_2)
        self.stopBtn.setObjectName("stopBtn")
        self.gridLayout_2.addWidget(self.stopBtn, 1, 1, 1, 1)
        self.exportBtn = QtWidgets.QPushButton(parent=self.widget_2)
        self.exportBtn.setObjectName("exportBtn")
        self.gridLayout_2.addWidget(self.exportBtn, 1, 2, 1, 1)
        self.backBtn = QtWidgets.QPushButton(parent=self.widget_2)
        self.backBtn.setObjectName("backBtn")
        self.gridLayout_2.addWidget(self.backBtn, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.verticalLayout_5.addWidget(self.resultPageWidget)
        self.stackedWidget.addWidget(self.resultPage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.bodyBottom)
        self.gridLayout.addWidget(self.Body, 1, 0, 1, 2)
        self.Header = QtWidgets.QFrame(parent=self.centralwidget)
        self.Header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.Header)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_5 = QtWidgets.QLabel(parent=self.Header)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.widget_5 = QtWidgets.QWidget(parent=self.Header)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_4.setText("")
        # self.label_4.setPixmap(QtGui.QPixmap("/home/ay0ub/Desktop/python/pyqt-projects/linkedinScraper/views/../assets/images/botintgram.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.gridLayout.addWidget(self.Header, 0, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignTop)
        self.Footer = QtWidgets.QFrame(parent=self.centralwidget)
        self.Footer.setMinimumSize(QtCore.QSize(0, 0))
        self.Footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Footer.setObjectName("Footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Footer)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusLbl = QtWidgets.QLabel(parent=self.Footer)
        self.statusLbl.setStyleSheet("color:white;")
        self.statusLbl.setObjectName("statusLbl")
        self.horizontalLayout_3.addWidget(self.statusLbl, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.authorLbl = QtWidgets.QLabel(parent=self.Footer)
        self.authorLbl.setObjectName("authorLbl")
        self.horizontalLayout_3.addWidget(self.authorLbl, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.gridLayout.addWidget(self.Footer, 2, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignBottom)
        LinkedinScraper.setCentralWidget(self.centralwidget)

        self.retranslateUi(LinkedinScraper)
        QtCore.QMetaObject.connectSlotsByName(LinkedinScraper)

    def retranslateUi(self, LinkedinScraper):
        _translate = QtCore.QCoreApplication.translate
        LinkedinScraper.setWindowTitle(_translate("LinkedinScraper", "Linkedin Scraper"))
        self.titleBodyLbl.setText(_translate("LinkedinScraper", "Craft Your Target"))
        self.titleBodyLbl.setProperty("class", _translate("LinkedinScraper", "titleBodyLbl"))
        self.label.setText(_translate("LinkedinScraper", "Job Title"))
        self.jobTitleLineEdit.setPlaceholderText(_translate("LinkedinScraper", "e.g: Laravel developer"))
        self.label_2.setText(_translate("LinkedinScraper", "Country"))
        self.label_3.setText(_translate("LinkedinScraper", "City"))
        self.cityLineEdit.setPlaceholderText(_translate("LinkedinScraper", "e.g : paris"))
        self.label_6.setText(_translate("LinkedinScraper", "Keywords to include (optional)"))
        self.includeKeyLineEdit.setPlaceholderText(_translate("LinkedinScraper", "e.g : laravel expert developer "))
        self.label_7.setText(_translate("LinkedinScraper", "Keywords to exclude (optional)"))
        self.excludeKeyLineEdit.setPlaceholderText(_translate("LinkedinScraper", "e.g : nodejs developer"))
        self.startScraperBtn.setText(_translate("LinkedinScraper", "Start Scraping"))
        self.emailsListWidget.setSortingEnabled(True)
        self.label_8.setText(_translate("LinkedinScraper", "Running..."))
        self.label_8.setProperty("class", _translate("LinkedinScraper", "actionStatusLbl__running"))
        self.stopBtn.setText(_translate("LinkedinScraper", "Stop"))
        self.stopBtn.setProperty("class", _translate("LinkedinScraper", "danger"))
        self.exportBtn.setText(_translate("LinkedinScraper", "Export"))
        self.backBtn.setText(_translate("LinkedinScraper", "Back"))
        self.backBtn.setProperty("class", _translate("LinkedinScraper", "warning"))
        self.label_9.setText(_translate("LinkedinScraper", "Extracted : 0"))
        self.label_5.setText(_translate("LinkedinScraper", "Linkedin Scraper "))
        self.label_5.setProperty("class", _translate("LinkedinScraper", "titleLbl"))
        self.statusLbl.setText(_translate("LinkedinScraper", "Silent waters run deep."))
        self.statusLbl.setProperty("class", _translate("LinkedinScraper", "quoteLbl"))
        self.authorLbl.setText(_translate("LinkedinScraper", "By : A00N"))
